// Deliberately fictional fixtures. Replace this module with the product API adapter.
export const companies = [
  {
    id: "forma",
    name: "Forma",
    tagline: "Making room for better work.",
    sector: "Workplace technology",
    color: "#465848",
    background: "#edf0e7",
    size: "51–200 people",
    founded: "2019",
    location: "Bengaluru, India",
    description:
      "We build thoughtful tools that help teams do their best work, wherever work happens. Our small, multidisciplinary team believes great software should feel simple, useful, and a little more human.",
  },
  {
    id: "layers",
    name: "Layers",
    tagline: "A new canvas for collaboration.",
    sector: "Design & collaboration",
    color: "#726299",
    background: "#eeebf5",
    size: "11–50 people",
    founded: "2021",
    location: "London, United Kingdom",
    description:
      "Layers brings creative teams together around the work they love. We are building a calmer, more collaborative space for ideas to take shape.",
  },
  {
    id: "orbit",
    name: "Orbit",
    tagline: "Good ideas deserve a bigger orbit.",
    sector: "Financial technology",
    color: "#bd613f",
    background: "#f8e9de",
    size: "201–500 people",
    founded: "2017",
    location: "Mumbai, India",
    description:
      "We help independent businesses move money with confidence. Our team combines care for craft with a practical approach to solving everyday financial problems.",
  },
  {
    id: "northstar",
    name: "Northstar",
    tagline: "Technology with a sense of direction.",
    sector: "Climate technology",
    color: "#376a7b",
    background: "#e5eff2",
    size: "51–200 people",
    founded: "2020",
    location: "Remote, worldwide",
    description:
      "We make environmental data easier to understand and act on. Our distributed team builds useful tools for people working on the planet’s most important challenges.",
  },
  {
    id: "monograph",
    name: "Monograph",
    tagline: "Stories that bring people closer.",
    sector: "Media & publishing",
    color: "#994e64",
    background: "#f4e7eb",
    size: "11–50 people",
    founded: "2022",
    location: "New York, United States",
    description:
      "We are an independent publishing platform for people with something to say. We care about original thinking, beautiful tools, and meaningful connections.",
  },
  {
    id: "arc",
    name: "Arc",
    tagline: "Building what comes next.",
    sector: "Developer tools",
    color: "#48617e",
    background: "#e7edf6",
    size: "51–200 people",
    founded: "2018",
    location: "Hyderabad, India",
    description:
      "Arc helps developers turn ambitious ideas into reliable products. We build tools that remove complexity and give teams more time to create.",
  },
];
const design_responsibilities = [
  "Own the end-to-end design of meaningful product experiences, from early exploration to the final details.",
  "Work closely with engineering and product partners to turn complex problems into clear, useful solutions.",
  "Talk to customers, test your ideas, and use what you learn to make the product better.",
  "Help evolve a thoughtful design system that brings consistency without limiting creativity.",
];
const design_requirements = [
  "A portfolio that shows how you think, the decisions you made, and the impact of your work.",
  "Experience designing and shipping digital products with a multidisciplinary team.",
  "A strong eye for interaction, typography, layout, and accessible design.",
  "Comfort sharing work early, giving considered feedback, and learning from others.",
];
export const jobs = [
  {
    id: "senior-product-designer",
    title: "Senior Product Designer",
    company: "forma",
    category: "Design",
    location: "Bengaluru, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Senior",
    salary_min: 2800000,
    salary_max: 4000000,
    currency: "INR",
    skills: ["Product design", "Figma", "Design systems"],
    posted: 1,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Help us make everyday work feel a little more human. Shape thoughtful experiences used by teams around the world.",
    responsibilities: design_responsibilities,
    requirements: design_requirements,
  },
  {
    id: "frontend-engineer",
    title: "Frontend Engineer",
    company: "layers",
    category: "Engineering",
    location: "Worldwide",
    mode: "Remote",
    type: "Full-time",
    level: "Mid-level",
    salary_min: 85000,
    salary_max: 115000,
    currency: "USD",
    skills: ["React", "TypeScript", "Accessibility"],
    posted: 0,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Build expressive, beautifully fast interfaces for the next generation of creative collaboration.",
    responsibilities: [
      "Build accessible, responsive interfaces in TypeScript and React.",
      "Partner with designers to bring polished interactions to life.",
      "Improve application performance and contribute to shared UI components.",
      "Take part in thoughtful code reviews and technical planning.",
    ],
    requirements: [
      "Experience shipping web applications with a modern frontend framework.",
      "Strong knowledge of semantic HTML, CSS, and JavaScript.",
      "An interest in performance, accessibility, and the details of interaction.",
      "Clear written communication in a distributed team.",
    ],
  },
  {
    id: "product-manager",
    title: "Product Manager",
    company: "orbit",
    category: "Product",
    location: "Mumbai, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Mid-level",
    salary_min: 2400000,
    salary_max: 3600000,
    currency: "INR",
    skills: ["Product strategy", "Research", "Analytics"],
    posted: 2,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Bring clarity to everyday finance. Work with a small team to build products independent businesses love.",
    responsibilities: [
      "Define product priorities through customer research and data.",
      "Work with design and engineering to scope useful, achievable releases.",
      "Measure outcomes and communicate progress clearly.",
      "Build a deep understanding of independent business needs.",
    ],
    requirements: [
      "Experience taking digital products from discovery to launch.",
      "Strong analytical thinking and clear communication.",
      "A collaborative approach to decisions and prioritization.",
      "Curiosity about how small businesses work.",
    ],
  },
  {
    id: "brand-designer",
    title: "Brand Designer",
    company: "monograph",
    category: "Design",
    location: "Worldwide",
    mode: "Remote",
    type: "Contract",
    level: "Mid-level",
    salary_min: 65000,
    salary_max: 85000,
    currency: "USD",
    skills: ["Brand identity", "Typography", "Illustration"],
    posted: 3,
    tier: "Free",
    application: "Easy apply",
    summary:
      "Give independent voices an unmistakable visual language. Shape the next chapter of our brand.",
    responsibilities: design_responsibilities,
    requirements: design_requirements,
  },
  {
    id: "senior-backend-engineer",
    title: "Senior Backend Engineer",
    company: "arc",
    category: "Engineering",
    location: "Hyderabad, India",
    mode: "Remote",
    type: "Full-time",
    level: "Senior",
    salary_min: 3200000,
    salary_max: 4800000,
    currency: "INR",
    skills: ["Go", "PostgreSQL", "APIs"],
    posted: 1,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Build dependable infrastructure that lets developers focus on their next big idea.",
    responsibilities: [
      "Design clear, well-documented APIs.",
      "Build and operate reliable services with Go and PostgreSQL.",
      "Improve observability and performance as the platform grows.",
      "Work with a small team that values pragmatic technical decisions.",
    ],
    requirements: [
      "Experience running backend services in production.",
      "Strong understanding of relational databases and API design.",
      "An interest in reliability, security, and developer experience.",
      "Comfort collaborating asynchronously.",
    ],
  },
  {
    id: "climate-data-analyst",
    title: "Climate Data Analyst",
    company: "northstar",
    category: "Data",
    location: "London, United Kingdom",
    mode: "Hybrid",
    type: "Full-time",
    level: "Mid-level",
    salary_min: 55000,
    salary_max: 72000,
    currency: "GBP",
    skills: ["Python", "SQL", "Data visualization"],
    posted: 4,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Turn complex environmental data into decisions that make a difference.",
    responsibilities: [
      "Analyze environmental datasets and document meaningful insights.",
      "Create clear visualizations with the product team.",
      "Build repeatable data validation workflows.",
      "Share findings with technical and non-technical partners.",
    ],
    requirements: [
      "Experience analyzing data using Python and SQL.",
      "An eye for clear, honest data visualization.",
      "Careful attention to data quality and reproducibility.",
      "Interest in climate and environmental challenges.",
    ],
  },
  {
    id: "ux-researcher",
    title: "UX Researcher",
    company: "forma",
    category: "Design",
    location: "Bengaluru, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Mid-level",
    salary_min: 1800000,
    salary_max: 2600000,
    currency: "INR",
    skills: ["User research", "Usability testing", "Synthesis"],
    posted: 2,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Help us listen more closely. Bring the needs of real people into every product decision.",
    responsibilities: design_responsibilities,
    requirements: design_requirements,
  },
  {
    id: "growth-marketer",
    title: "Growth Marketer",
    company: "layers",
    category: "Marketing",
    location: "London, United Kingdom",
    mode: "Remote",
    type: "Full-time",
    level: "Mid-level",
    salary_min: 50000,
    salary_max: 68000,
    currency: "GBP",
    skills: ["Content strategy", "SEO", "Analytics"],
    posted: 5,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Connect thoughtful creative teams with a better way to work together.",
    responsibilities: [
      "Create useful campaigns that introduce our product to new teams.",
      "Experiment with content and organic acquisition channels.",
      "Measure results and share what you learn.",
      "Partner with product and design on a consistent brand experience.",
    ],
    requirements: [
      "Experience in product marketing or sustainable growth.",
      "Strong writing and analytical skills.",
      "A practical approach to experiments and measurement.",
      "A feel for creative communities and their needs.",
    ],
  },
  {
    id: "junior-product-designer",
    title: "Junior Product Designer",
    company: "orbit",
    category: "Design",
    location: "Mumbai, India",
    mode: "On-site",
    type: "Full-time",
    level: "Entry-level",
    salary_min: 900000,
    salary_max: 1400000,
    currency: "INR",
    skills: ["Figma", "Interaction design", "Prototyping"],
    posted: 0,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Grow your craft with a team that makes space for curiosity, fresh ideas, and thoughtful feedback.",
    responsibilities: design_responsibilities,
    requirements: [
      "A portfolio of projects that demonstrates your approach to design.",
      "Familiarity with Figma and common prototyping workflows.",
      "Curiosity, care for detail, and openness to feedback.",
      "Personal projects and non-traditional learning paths are welcome.",
    ],
  },
  {
    id: "community-lead",
    title: "Community Lead",
    company: "monograph",
    category: "Operations",
    location: "New York, United States",
    mode: "Hybrid",
    type: "Part-time",
    level: "Mid-level",
    salary_min: 40000,
    salary_max: 55000,
    currency: "USD",
    skills: ["Community", "Events", "Writing"],
    posted: 6,
    tier: "Free",
    application: "Easy apply",
    summary:
      "Make our growing community of independent writers feel a little more connected.",
    responsibilities: [
      "Plan welcoming community gatherings.",
      "Build relationships with writers and creative partners.",
      "Share community feedback with our product team.",
      "Create useful resources for new members.",
    ],
    requirements: [
      "Experience building or supporting a community.",
      "Thoughtful writing and interpersonal skills.",
      "A welcoming, inclusive approach.",
      "Interest in independent publishing.",
    ],
  },
  {
    id: "design-systems-designer",
    title: "Design Systems Designer",
    company: "arc",
    category: "Design",
    location: "Worldwide",
    mode: "Remote",
    type: "Contract",
    level: "Senior",
    salary_min: 90000,
    salary_max: 120000,
    currency: "USD",
    skills: ["Design systems", "Figma", "Accessibility"],
    posted: 3,
    tier: "Premium",
    application: "Easy apply",
    summary:
      "Connect the details. Build a design language that helps our product feel like one considered experience.",
    responsibilities: design_responsibilities,
    requirements: design_requirements,
  },
  {
    id: "product-design-intern",
    title: "Product Design Intern",
    company: "northstar",
    category: "Design",
    location: "Bengaluru, India",
    mode: "Remote",
    type: "Internship",
    level: "Entry-level",
    salary_min: 360000,
    salary_max: 480000,
    currency: "INR",
    skills: ["Figma", "Prototyping", "Research"],
    posted: 1,
    tier: "Free",
    application: "Easy apply",
    summary:
      "Start your design journey with meaningful work and a team that invests in your growth.",
    responsibilities: design_responsibilities,
    requirements: [
      "A few projects that show curiosity and design thinking.",
      "Basic experience with Figma or a similar design tool.",
      "An interest in accessible, useful digital products.",
      "Willingness to ask questions and learn with the team.",
    ],
  },
];
export const default_profile = {
  name: "Alex Morgan",
  title: "Product Designer",
  location: "Bengaluru, India",
  email: "alex@example.com",
  about:
    "I’m a product designer who enjoys turning complex problems into simple, thoughtful experiences. Over the past six years, I’ve worked with ambitious teams to build products that feel useful, considered, and human.\n\nI’m especially drawn to early-stage products, design systems, and teams that make room for curiosity. Outside of Figma, you’ll usually find me with a camera or a good book.",
  website: "alexmorgan.design",
  experience: "6 years",
  expected: "₹28–36 LPA",
  notice: "30 days",
  open: true,
  visible: true,
  salary_private: true,
  resume_private: true,
  skills: [
    "Product design",
    "Design systems",
    "Figma",
    "Interaction design",
    "User research",
    "Prototyping",
    "Accessibility",
    "Visual design",
  ],
  roles: "Senior Product Designer, Product Designer",
  work_mode: "Remote or hybrid",
};
export function get_company(id) {
  return companies.find((company) => company.id === id) ?? companies[0];
}
export function salary(job) {
  if (job.currency === "INR")
    return `₹${job.salary_min / 100000}–${job.salary_max / 100000} LPA`;
  return `${job.currency === "USD" ? "$" : "£"}${job.salary_min / 1000}k–${job.salary_max / 1000}k / year`;
}
export function posted(days) {
  return days === 0 ? "Today" : `${days}d ago`;
}
