export type company_data = {
  id: string;
  name: string;
  tagline: string;
  sector: string;
  color: string;
  background: string;
  size: string;
  founded: string;
  location: string;
  description: string;
};
export type job_data = {
  id: string;
  title: string;
  company: string;
  category: string;
  location: string;
  mode: string;
  type: string;
  level: string;
  salary_min: number;
  salary_max: number;
  currency: "INR" | "USD" | "GBP";
  skills: string[];
  posted: number;
  tier: "Free" | "Premium";
  application: "Easy apply" | "External";
  summary: string;
  responsibilities: string[];
  requirements: string[];
};
export type profile_data = {
  name: string;
  title: string;
  location: string;
  email: string;
  about: string;
  website: string;
  experience: string;
  expected: string;
  notice: string;
  open: boolean;
  visible: boolean;
  salary_private: boolean;
  resume_private: boolean;
  skills: string[];
  roles: string;
  work_mode: string;
};
export type search_filters = {
  query: string;
  location: string;
  modes: string[];
  types: string[];
  categories: string[];
  levels: string[];
  easy: boolean;
  saved: boolean;
  sort: string;
  currency: string;
  min_salary: number;
};
